### ISSUE TITLE
Type error in sasl-xoauth2-token-tool

### ISSUE THREAD

**Issue by whitemice** [tarickb/sasl-xoauth2#44]
sasl-xoauth2-token-tool does not run on openSUSE LEAP 15.4 (python3-3.6.15-150300.10.27.1.x86_64)

~~~
sasl-xoauth2-token-tool get-token outlook --client-id=b97a6896-8de5-4e49-9f7c-07365f3ef021 /etc/tokens/mormail@micore.us
Traceback (most recent call last):
  File "./scripts/sasl-xoauth2-token-tool", line 184, in <module>
    required=True,
  File "/usr/lib64/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
~~~

**Comment by ImAnOwl** [comment]
You need to put the word "outlook" after the client id :)
